# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nabajyotiworkspace
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-nodejs-project
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-project

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: arn:aws:s3:::s3-image-lambda-demo/*

plugins:
  - serverless-offline
  
functions:
  api:
    handler: lambda-api.handler
    events:
      - httpApi: "*"

  imageProcessor:
    handler: lambda-s3.triggerCopy
    events:
      - s3:
          bucket: s3-image-lambda-demo
          event: s3:ObjectCreated:*
          rules:
            - prefix: upload/
          existing: true  